### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by nekiter** [Guttz/life-journal-frontend#1]
I can't understand what is this project, can u please create a readme?

**Comment by Guttz** [comment]
For now, there is a 1 and a half long line in the beginning of the README explaining what this project is. 

Soon, when I release the backend, I'll detail it a bit more. You can also open a PR if you are interested. Thanks!

**Comment by Guttz** [comment]
For now, there is a 1,5-long line in the beginning of the README explaining what this project is.

Soon, when I release the backend, I'll detail it a bit more. You can also open a PR if you are interested. Thanks!
